[package]
name = "codedx-client"
version = "0.1.0"
authors = ["Dylan Halperin <dylan@dylemma.io>"]

[dependencies]
rand = "0.3.16"
clap = "2.26.2"
hyper = "0.11"
futures = "0.1"
maplit = "0.1.4"
tokio-core = "0.1"
url = "1.5.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"