[package]
name = "codedx-client"
version = "0.1.0"
authors = ["Dylan Halperin <dylan@dylemma.io>"]

[dependencies]
chrono = "0.4"
clap = "2.26.2"
hyper = "0.11"
maplit = "0.1.4"
url = "1.5.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

# waiting for https://github.com/seanmonstar/reqwest/pull/190 to be released
reqwest = { git = "https://github.com/seanmonstar/reqwest", branch = "master"}